### ISSUE TITLE
Force render glossary table of entire contents of `glossary.yml`

### ISSUE THREAD

**Issue by jfy133** [debruine/glossary#4]
I'm playing around with this package (really nice and working so far - thank you!) in quarto.

One thing I can't get to work (or is not yet supported), is to have the an entire `glossary.yml` to be loaded and displayed when invoking `glossary_table()`.

My logic is that I find it slightly redundant to have both the hover/click terms but also a table at the end of the same page/section. 

In my case I would like to have the hover/click terms on each page, and then one final independent 'glossary' page at the end of my document that lists all terms (i.e., everything within `glossary.yml`).

I could I guess hack around it by having the all `glossary()` text on the page but hidden (e.g. changing the font to white), and then invoke the table below this, but this seems like it's somewhat overkill. 

Would it be possible to add functionality to `glossary_table()` so you tell it to just render a table of everything within a given file (rather than what's being 'quoted' on that page).

Is this currently possible, or would it be possible to be added?

**Comment by debruine** [comment]
Thanks! There's a new function now called `glossary_load_all()` that does this. You can get the dev version to test it with the code below, and I'll send it to CRAN soon.

```
devtools::install_github("debruine/glossary")
```

**Comment by jfy133** [comment]
Nice, thank you very much @debruine  :D! :tada:
