### ISSUE TITLE
Glossary Table Includes Any Term with a Word In it

### ISSUE THREAD

**Issue by CNSteltenpohl** [debruine/glossary#5]
I'm working on the open qualitative methods book and am putting some placeholder text in to get things started. Our glossary has an entry for positionality and an entry for positionality statement. In the text I copied over from someone's draft, she referenced positionality specifically, but the table includes both positionality and positionality statement. While positionality statement could potentially show up in this chapter eventually, it's not currently being called. It also doesn't seem to show either definition in the table, and when I click on the text in the paragraph, it doesn't show anything either. (Positionality should show up as "some text" and positionality statement should show up as "some other text.")

I am using booktem but this seems like it might be a glossary-specific issue? I can repost under booktem if it's actually a booktem issue!

<img width="756" alt="Screenshot 2023-09-01 at 5 29 12 PM" src="https://github.com/debruine/glossary/assets/139169603/9716fc9b-ab44-462d-96dd-28153c8f7f0a">

Thanks for these packages by the way. It's been really fun to work with so far!

**Comment by debruine** [comment]
Thanks! That should be fixed in the dev version you can download here:

```
devtools::install_github("debruine/glossary")
```

I'll send this fix (and some new additions for quarto books) to CRAN soon.
